#ifndef defines_h
#define defines_h
#define DEBUG 0

#define WINDOW_WIDTH 500
#define WINDOW_HEIGHT 600
#define DRAW_GRID 0

#define TETRINOSIZE 20
#define BOARD_COLUMNS 11
#define BOARD_ROWS 20
#define BOARD_COLUMNS_PADDING 3
#define BOARD_WIDTH BOARD_COLUMNS * TETRINOSIZE
#define BOARD_HEIGHT BOARD_ROWS * TETRINOSIZE

#define BOARD_X_CENTER (BOARD_COLUMNS + BOARD_COLUMNS_PADDING * 2) / 2 * TETRINOSIZE
#define BOARD_Y_CENTER (BOARD_ROWS + 1) * TETRINOSIZE / 2

#define BOARD_X WINDOW_WIDTH / 2 - BOARD_X_CENTER
#define BOARD_Y WINDOW_HEIGHT / 2 - BOARD_Y_CENTER
#define ONGROUND_TIME_MIN 0.01

#define LEFT_OF_BOARD BOARD_X + 3 * TETRINOSIZE
#define BOTTOM_OF_BOARD BOARD_Y + BOARD_HEIGHT
#define TOP_OF_BOARD BOARD_Y
#define RIGHT_OF_BOARD BOARD_X + 2 * TETRINOSIZE + BOARD_WIDTH

#define I 1
#define O 2
#define T 3
#define J 4
#define L 5
#define S 6
#define Z 7

#endif