#ifndef defines_h
#define defines_h
#define DEBUG 1

#define WINDOW_WIDTH 500
#define WINDOW_HEIGHT 600
#define DRAW_GRID 1

#define TETRINOSIZE 20
#define BOARD_COLUMNS 10
#define BOARD_ROWS 20
#define BOARD_WIDTH BOARD_COLUMNS * TETRINOSIZE
#define BOARD_HEIGHT BOARD_ROWS * TETRINOSIZE

#define BOARD_X (WINDOW_WIDTH / 2 - BOARD_WIDTH/2)
#define BOARD_Y (WINDOW_HEIGHT / 2 - BOARD_HEIGHT/2)
#define ONGROUND_TIME_MIN 0.01

#define LEFT_OF_BOARD BOARD_X
#define BOTTOM_OF_BOARD BOARD_Y + BOARD_HEIGHT
#define TOP_OF_BOARD BOARD_Y
#define RIGHT_OF_BOARD BOARD_X + BOARD_WIDTH


#endif